# ~/.config/starship.toml
# Custom configuration with pale blue/denim + pale yellow + cherry red

format = """
$directory\
$git_branch\
$git_status\
$c\
$cpp\
$lua\
$zig\
$cmake\
$cmd_duration\
$character"""

[character]
success_symbol = "[❯](fg:#87ceeb bold)"
error_symbol = "[❯](fg:#dc143c bold)"

[directory]
style = "fg:#87ceeb bold"
truncation_length = 4
truncate_to_repo = false
format = "[$path]($style) "

[git_branch]
format = "[$symbol$branch]($style) "
style = "fg:#f0e68c"
symbol = " "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "fg:#fff59d"
modified = "*"
staged = "+"
untracked = "?"
ahead = "⇡"
behind = "⇣"
conflicted = "!"
deleted = "✘"

# Language-specific modules for your development stack
[c]
format = "[$symbol($version)]($style) "
style = "fg:#87ceeb"
symbol = " "

[cpp]
format = "[$symbol($version)]($style) "
style = "fg:#87ceeb"
symbol = " "

[lua]
format = "[$symbol($version)]($style) "
style = "fg:#4682b4"
symbol = " "

[zig]
format = "[$symbol($version)]($style) "
style = "fg:#f0e68c"
symbol = " "

[cmake]
format = "[$symbol($version)]($style) "
style = "fg:#4682b4"
symbol = "△ "

[cmd_duration]
format = "[⏱ $duration]($style) "
style = "fg:#f0e68c"
min_time = 2000

# Disable modules you don't need for performance
[aws]
disabled = true
[gcloud]
disabled = true
[docker_context]
disabled = true
[kubernetes]
disabled = true
